### ISSUE TITLE
"No path specified in plugin.ini" when trying to run "list/check plugins."

### ISSUE THREAD

**Issue by minorsecond** [cytopia/redmine-like-a-boss#1]
Steps taken:

Clone
git submodule init && git submodule update
./redmine-like-a-boss.sh

Enter option '2'

A list of plugins scrolls by with "no path specified in plugin.ini" in red. The same issue occurs with themes, too.

**Comment by cytopia** [comment]
What operating system are you on?

Could you try to replace `#!/bin/sh -u` with `#!/usr/bin/env bash`, just to see if that works?

**Comment by minorsecond** [comment]
I'm running Debian Jessie.

I did that and the only thing that changed is that now the available plugins menu remains on screen until it receives user input.

**Comment by cytopia** [comment]
It works on my Mac with 

```
$ bash --version
GNU bash, version 4.3.46(1)-release (x86_64-apple-darwin15.5.0)
```

and on my CentOS 7 server

``` shell
$ bash --version
GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)
```

I am assuming that mayby redmine-like-a-boss.sh:138 has problems parsing the ini file

```
_ini_get_section_value() {
...
}
```

It needs grep, sed and awk.
On my Mac:

``` shell
$ awk --version | head -1
GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4-p1, GNU MP 6.1.1)

$ sed --version | head -1
sed (GNU sed) 4.2.2

$ grep --version
grep (BSD grep) 2.5.1-FreeBSD
```

And on CentOS:

``` shell
$ awk --version | head -1
GNU Awk 4.0.2

$ sed --version | head -1
sed (GNU sed) 4.2.2


$ grep --version | head -1
grep (GNU grep) 2.20
```

Could you also check `plugin.ini` maybe during the clone the linefeeds have been replaced by CRLF?.

**Comment by minorsecond** [comment]
Interesting. Awk was installed, but I couldn't get the version, so I installed "gawk," which fixed it. 

Thanks for your help! This tool looks awesome.
